// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var embedCodeGenerator, thumbnailCodeGenerator, videoID;
    videoID = ["_BwwkFjAxzU", "YFp4X5Ivixs", "VkMiaSc4F4o", "b2dam2LjUV0", "YoiE_8Pu7zo", "c9VOjwb1tQ4"];
    console.log("videoID[1]: " + videoID[1]);
    embedCodeGenerator = function(thumbNumber) {
      return '<iframe width="1366" height="768" src="http://www.youtube.com/embed/' + videoID[thumbNumber] + '" frameborder="0" allowfullscreen></iframe>';
    };
    thumbnailCodeGenerator = function(thumbNumber) {
      return "<img src='http://img.youtube.com/vi/" + videoID[thumbNumber] + "/0.jpg'></img>";
    };
    console.log("embedCodeGenerator: " + embedCodeGenerator(1));
    console.log("thumbnailCodeGenerator: " + thumbnailCodeGenerator(1));
    return $(".thumbnails").on("click", function(e) {
      var id;
      id = $(this).attr("id");
      return $('.mainVideo').html(embedCodeGenerator(id));
    });
  });

}).call(this);

//# sourceMappingURL=js.map
